"""Initial schema

Revision ID: e06b370741d6
Revises: 
Create Date: 2025-11-19 22:11:13.239924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06b370741d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellidos', sa.String(length=255), nullable=False),
    sa.Column('nombre_normalized', sa.String(length=255), nullable=False),
    sa.Column('apellidos_normalized', sa.String(length=255), nullable=False),
    sa.Column('asistencia', sa.String(length=50), nullable=False),
    sa.Column('acompanado', sa.String(length=10), nullable=False),
    sa.Column('adultos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ninos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('autobus', sa.String(length=50), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_normalized', 'apellidos_normalized', name='uix_guests_normalized_names')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    # ### end Alembic commands ###
